main/account/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^validate_email/$', views.send_email_validation, name='send_validate_email'),
    url(r'^validate_email/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.validate_email, name='validate_email'),
    url(r'^$', views.profile, name='myprofile'), #this is a logged in user's profile page
    url(r'^(?P<user_id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^settings/$', views.user_settings, name='settings'),
]

main/main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^messages/', include('user_messages.urls', namespace='messages')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^account/', include('account.urls', namespace='account')), #user profile page and other account actions
    url(r'^$', views.index, name='index'),  #main page
    url(r'^admin/', admin.site.urls),
]

main/posts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<post_id>[0-9]+)/$', views.post_page, name='post'),
    url(r'^(?P<post_id>[0-9]+)/delete/$', views.delete_post, name='delete_post'),
    url(r'^(?P<post_id>[0-9]+)/settings/$', views.post_settings, name='settings'),
    url(r'^comment/(?P<post_id>[0-9]+)/$', views.comment, name='comment'),
    url(r'^comment/(?P<comment_id>[0-9]+)/delete/$', views.delete_comment, name='delete_comment'),
    url(r'^ads/((?P<category>[0-9]+)/)?$', views.ads, name='ads'),
    url(r'^newpost/$', views.new_post, name='newpost'),
    url(r'^categories/$', views.categories, name='categories'),
    url(r'^test/$', views.test, name='test'), #temporary test page
]

main/user_messages/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.mailbox, name='mailbox'),
    url(r'^send/$', views.send_user_mail, name='send_user_mail'),
    url(r'^delete_mail/(?P<mail_id>[0-9]+)/$', views.delete_mail, name='delete_mail'),
]

main/posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from account.models import User

import uuid
import os

def unique_post_name(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)    #this generates a unique id for the filename
    return os.path.join('posts', filename)

class Categories(models.Model):
    title = models.CharField(max_length=40)
    description = models.CharField(max_length=255)
    image = models.ImageField(upload_to='posts/')

    def __str__(self):
        return self.title

class Posts(models.Model):
    # all foreign dependencies
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, default=1)   #default is unknown category
    poster = models.ForeignKey(User, on_delete=models.CASCADE, default=1)           #default is unknown user    NOTE: in practice, these should never be used

    # own attributes
    title = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0) #maybe change this type of field later
    description = models.TextField(null=True)
    offering = models.BooleanField(default=True)    #false means they are wanting
    time = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title

class Comments(models.Model):
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    text = models.CharField(max_length=511)
    time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

# here is a simple model that allows us to store an arbitrary amount of images per post
class PostImages(models.Model):
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)

    image = models.ImageField(upload_to=unique_post_name, default='posts/no_image_available.jpg')

main/posts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

from .models import Categories, Posts, PostImages, Comments
from main.views import image_validation
from user_messages.models import Mail, send_notification


@login_required
def new_post(request):
    """ a view to handle and present the new post form
        post fields include:

        1
        - adtitle (text)
        - type (radio: offering/wanting)
        - price (investigate this input more)
        - NOTE: NAME NEEDED description

        2
        - Image array (NEEDS DIFFERENT NAMES)

        4
        - detail (selection, basically a category) THIS VALUE SHOULD BE THE CATEGORY KEY
        """

    errors = dict()
    categories = Categories.objects.all()

    # process form here
    if request.method == "POST":

        # VALIDATE ALL FIELDS

        poster = request.user.pk
        category = request.POST['detail']
        title = request.POST['adtitle']

        try:
            price = float(request.POST['price'])
            if len(request.POST['price']) > 9 or price < 0:
                errors['price'] = 'Please enter a valid price.'
        except ValueError:
            # send error message to post form
            errors['price'] = 'Please enter a valid price.'

        description = request.POST['description']
        offering = True if request.POST['type'] == 'offering' else False

        files = []
        if request.FILES.get('files', None):
            files = request.FILES.getlist('files')
            # number of images
            if len(files) > 5:
                errors['images'] = "You can only upload up to 5 pictures per post."
            elif not image_validation(files):
                # image extensions
                errors['images'] = 'You can only upload image file types.'

        if errors:
            return render(request, 'posts/post2.html', {'errors': errors, 'categories': categories})

        # SAVE TO DB

        new_post = Posts(category_id=category, poster_id=poster, title=title, price=price, description=description, offering=offering)
        new_post.save()

        #and save all of the images:
        if files:
            for image in files:
                new_image = PostImages(post_id=new_post.pk, image=image)
                new_image.save()
        # or just save one default image if no uploads
        else:
            new_image = PostImages(post_id=new_post.pk)
            new_image.save()

        return HttpResponseRedirect(reverse('posts:post', kwargs={'post_id': new_post.pk}))

    # render the page with any errors or just a plain form
    return render(request, 'posts/post.html', {'errors': errors, 'categories': categories})

@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Posts, pk=post_id, poster_id=request.user.pk)

    post.delete()

    return HttpResponseRedirect(reverse('account:myprofile'))

@login_required
def post_settings(request, post_id):
    post = get_object_or_404(Posts, pk=post_id, poster_id=request.user.pk)

    post.status = True if request.POST.get("status", None) else False
    post.save()

    return HttpResponseRedirect(reverse('posts:post', kwargs={'post_id': post_id}))

def ads(request, category):

    if category:
        # get posts with category key
        post_list = Posts.objects.filter(category=category)
    else:
        # get all posts
        post_list = Posts.objects.all()

    search = request.GET.get('search', '')
    post_list = post_list.filter(Q(title__icontains=search) | Q(description__icontains=search))
    post_list = post_list.order_by('-time')

    items_per_page = 8

    page_list = Paginator(post_list, items_per_page)

    """ Here is some code from https://docs.djangoproject.com/en/1.11/topics/pagination/ """
    current_page = request.GET.get('page', None)
    try:
        posts = page_list.page(current_page)
        current_page = int(current_page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = page_list.page(1)
        current_page = 1
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = page_list.page(page_list.num_pages)
        current_page = page_list.num_pages

    # do some calculations to find a number of next pages
    start_page = max(0, current_page - 3)
    end_page = min(page_list.num_pages, current_page + 3)
    page_range = range(start_page + 1, end_page + 1)

    return render(request, 'posts/ads.html', {'posts': posts, 'current_page': current_page, 'page_range': page_range})

@login_required
def comment(request, post_id):

    post = get_object_or_404(Posts, pk=post_id)

    if request.method == "POST":
        # process form
        comment = request.POST['comment']
        c = Comments(post_id=post_id, user_id=request.user.pk, text=comment)
        c.save()

        # send notification/message
        subject = request.user.username + " just commented on your post."
        message = request.user.username + ' commented on your post titled "' + post.title + '". They said "' + comment + '". Go check it out!'

        mail = Mail(sender_id=1, reciever_id=post.poster_id, subject=subject, content=message)
        send_notification(mail)

    return HttpResponseRedirect(reverse('posts:post', kwargs={'post_id': post_id}))

@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comments, pk=comment_id, user_id=request.user.pk)
    comment.delete()

    return HttpResponseRedirect(reverse('posts:post', kwargs={'post_id': comment.post_id}))


def post_page(request, post_id):
    post = get_object_or_404(Posts, pk=post_id)

    return render(request, 'posts/item.html', {'post': post})

def categories(request):
    categories = Categories.objects.all().order_by('-pk')

    return render(request, 'posts/categories.html', {'categories': categories})


def test(request):
    return render(request, 'posts/test.html')

main/templates/posts/categories.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  {% load thumbnail%}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Category</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">							<!-- W3schools font for side bar -->
    <link rel="shortcut icon" href="{% static 'img/Uregina.ico' %}"/>
    <link rel="stylesheet" href="{% static 'css/bigcategory.css' %}"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:100,300,400">   <!-- Google web font "Open Sans" -->
    <link rel="stylesheet" href="{% static 'font-awesome-4.5.0/css/font-awesome.min.css' %}">                <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">                                      <!-- Bootstrap style -->
    <link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}">                                   <!-- Templatemo style -->
    <link rel="stylesheet" href="{% static "css/login.css" %}">

    <style>
          .footer {
                  position: absolute;
                  right: 0;
                  bottom: 50;
                  left: 0;
                  padding: 5rem;
                  background-color: #ff9900;
                  text-align: center;
                  }
   </style>

</head>

    <body id="top" class="page-2">
      <!------------------------------------------------------------------------------- Side Bar ------------------------------------------------------------------------------>
        {% if request.user.is_authenticated %}
            <button id="sidebaricon" class="sidebar" onclick="sidebar_open()"><img class="sidebar" src="{{ request.user.profile_pic.url }}" alt="Avatar"></button>
			<div class="w3-sidebar w3-bar-block w3-animate-left" style="top:0px;background-color:rgba(0,0,0,0.4); color:grey; display:none;z-index:100005" id="mySidebar">
				<button class="login-close" onclick="sidebar_close()">&times;</button>
  				<img class="usericon" src="{{ request.user.profile_pic.url }}" alt="Avatar"><hr color="grey"/>
  				<a href="{% url 'account:myprofile' %}" style="background-color:transparent" class="w3-bar-item w3-button">User Profile</a>
  				<a href="{% url 'messages:mailbox' %}" style="background-color:transparent" class="w3-bar-item w3-button">Messaging</a>
				<hr color="grey"/>

				<a href="{% url 'posts:newpost' %}" style="background-color:transparent" class="w3-bar-item w3-button">Post Ad</a>
				<a href="{% url 'posts:ads' %}" style="background-color:transparent" class="w3-bar-item w3-button">Ads</a>

				<hr color="grey"/>
				<a href="{% url 'account:logout' %}" style="background-color:transparent" class="w3-bar-item w3-button">Logout</a>
			</div>
			<div class="w3-overlay w3-animate-opacity" onclick="sidebar_close()" style="cursor:pointer" id="myOverlay"></div>
      <script>
              function sidebar_open() {
                  document.getElementById("mySidebar").style.display = "block";
                  document.getElementById("myOverlay").style.display = "block";
                  document.getElementById("sidebaricon").style.display = "none";
              }
              function sidebar_close() {
                  document.getElementById("mySidebar").style.display = "none";
                  document.getElementById("myOverlay").style.display = "none";
                  document.getElementById("sidebaricon").style.display = "block";
              }
            </script>
            {% endif %}
 <!------------------------------------------------------------------------------- List of the titles ------------------------------------------------------------------------------>
        <div class="tm-navbar-container tm-navbar-container-dark">
            <nav class="navbar navbar-full navbar-fixed-top bg-inverse">
                <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#tmNavbar">
                    &#9776;
                </button>
                <div class="collapse navbar-toggleable-sm" id="tmNavbar">
                    <ul class="nav navbar-nav">
                        <li class="nav-item"><a href="{% url 'index' %}" class="nav-link external">Home</a></li>
                        <li class="nav-item"><a href="{% url 'posts:ads' %}" class="nav-link external">Most Recent</a></li>
                        <li class="nav-item"><a href="{% url 'posts:categories' %}" class="nav-link">Categories</a> </li>
                    </ul>
                </div>
            </nav>
        </div>
 <!------------------------------------------------------------------------------- Buy & Sell ------------------------------------------------------------------------------>

      <div class="container-fluid">

            <div class="row">
              <div id="Buy" class="tm-section">
                <div class="col-md-12">
                    <h1 class="text-xs-center blue-text tm-page-2-title">Categories</h1>
                    <p class="text-xs-center tm-page-2-p tm-page-2-subtitle">
                        All you daily needs <br>
                        start at UR-SALE.
                    </p>
                </div>
              </div>
            </div>

            <div class="row">
              {% for category in categories %}
              <div class="view view-tenth">
                {% thumbnail category.image 370x280 crop as thumb %}
              <img src="{{ thumb.url }}" width="{{ thumb.width }}" height="{{ thumb.height }}" alt="hey"/>
                <div class="mask">
                   <h2>{{ category.title }}</h2>
                    <p>{{ category.description|truncatechars:150 }}</p>
                   <a href="{% url 'posts:ads' %}{{ category.pk }}" class="info">Read More</a>
                 </label>
                </div>
              </div>
              {% endfor %}
            </div>


                <div class="tm-section" id="Buy">

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    <p class="text-xs-center tm-footer-text">Copyright &copy; 2017 UR-SALE</p>
                </div>
            </div>
        </div> <!-- .container -->

        <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>             <!-- jQuery (https://jquery.com/download/) -->
        <script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script> <!-- Tether for Bootstrap, http://stackoverflow.com/questions/34567939/how-to-fix-the-error-error-bootstrap-tooltips-require-tether-http-github-h -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>                 <!-- Bootstrap (http://v4-alpha.getbootstrap.com/) -->
        <script src="{% static 'js/jquery.singlePageNav.min.js' %}"></script>      <!-- Single Page Nav (https://github.com/ChrisWojcik/single-page-nav) -->
        <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>     <!-- Magnific pop-up (http://dimsemenov.com/plugins/magnific-popup/) -->


        <!-- Templatemo scripts -->
        <script>

            $(document).ready(function(){

                var mobileTopOffset = 54;
                var tabletTopOffset = 74;
                var desktopTopOffset = 79;
                var topOffset = desktopTopOffset;

                if($(window).width() <= 767) {
                    topOffset = mobileTopOffset;
                }
                else if($(window).width() <= 991) {
                    topOffset = tabletTopOffset;
                }

                /* Single page nav
                -----------------------------------------*/
                $('#tmNavbar').singlePageNav({
                    'currentClass' : "active",
                    offset : topOffset,
                    'filter': ':not(.external)'
                });

                if($(window).width() < 570) {
                    $('.tm-full-width-large-table').addClass('table-responsive');
                }
                else {
                    $('.tm-full-width-large-table').removeClass('table-responsive');
                }


                /* Collapse menu after click
                -----------------------------------------*/
                $('#tmNavbar a').click(function(){
                    $('#tmNavbar').collapse('hide');
                });


                /* Handle nav offset & table responsive upon window resize
                --------------------------------------------------------------*/
                $(window).resize(function(){

                    if($(window).width() < 768) {
                        topOffset = mobileTopOffset;
                    }
                    else if($(window).width() <= 991) {
                        topOffset = tabletTopOffset;
                    }
                    else {
                        topOffset = desktopTopOffset;
                    }

                    $('#tmNavbar').singlePageNav({
                        'currentClass' : "active",
                        offset : topOffset,
                        'filter': ':not(.external)'
                    });

                    if($(window).width() < 570) {
                        $('.tm-full-width-large-table').addClass('table-responsive');
                    }
                    else {
                        $('.tm-full-width-large-table').removeClass('table-responsive');
                    }
                });

            });

        </script>
    </body>
</html>

main/templates/posts/item.html
<!DOCTYPE html>
<html lang="en">

  <head>
    {% load static %}
    {% load thumbnail %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Shop Item</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'css/item1.css' %}" rel="stylesheet">
    <link href="{% static 'css/item2.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/item.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">                                     				<!-- login style -->
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <!-- index navigation -->

    <style>
    i{color:blue;}
    i:hover{color:orange;}
    </style>
  </head>

  <body>
    <!------------------------------------------------------------------------------- Side Bar ------------------------------------------------------------------------------>
      {% if request.user.is_authenticated %}
          <button style="z-index:1000000;" id="sidebaricon" class="sidebar" onclick="sidebar_open()"><img class="sidebar" src="{{ request.user.profile_pic.url }}" alt="Avatar"></button>
    <div class="w3-sidebar w3-bar-block w3-animate-left" style="top:0px;background-color:rgba(0,0,0,0.4); color:grey; display:none;z-index:100005" id="mySidebar">
      <button class="login-close" onclick="sidebar_close()">&times;</button>
        <img class="usericon" src="{{ request.user.profile_pic.url }}" alt="Avatar"><hr color="grey"/>
        <a href="{% url 'account:myprofile' %}" style="background-color:transparent" class="w3-bar-item w3-button">User Profile</a>
        <a href="{% url 'messages:mailbox' %}" style="background-color:transparent" class="w3-bar-item w3-button">Messaging</a>
      <hr color="grey"/>

      <a href="{% url 'posts:newpost' %}" style="background-color:transparent" class="w3-bar-item w3-button">Post Ad</a>
      <a href="{% url 'posts:ads' %}" style="background-color:transparent" class="w3-bar-item w3-button">Ads</a>

      <hr color="grey"/>
      <a href="{% url 'account:logout' %}" style="background-color:transparent" class="w3-bar-item w3-button">Logout</a>
    </div>
    <div class="w3-overlay w3-animate-opacity" onclick="sidebar_close()" style="cursor:pointer" id="myOverlay"></div>
    <script>
            function sidebar_open() {
                document.getElementById("mySidebar").style.display = "block";
                document.getElementById("myOverlay").style.display = "block";
                document.getElementById("sidebaricon").style.display = "none";
            }
            function sidebar_close() {
                document.getElementById("mySidebar").style.display = "none";
                document.getElementById("myOverlay").style.display = "none";
                document.getElementById("sidebaricon").style.display = "block";
            }
          </script>
          {% endif %}
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">UR-Sale</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'posts:ads' %}">Most Recent</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'posts:categories' %}">Categories</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <div class="col-lg-3">
          <h1 class="my-4">{{ post.category }}</h1>
          <div class="list-group">
            <a href="{% url 'posts:ads' %}{{ post.category.pk }}/" class="list-group-item active">{{ post.category }} ads</a>

          </div>
        </div>

        <!-- /.col-lg-3 -->
        <div class="col-lg-9">
          <div class="card mt-4">

             <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
            <ol class="carousel-indicators">
              {% for pic in post.postimages_set.all %}
              <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}"
              {% ifequal forloop.counter0 0 %}
              class="active"
              {% endifequal %}
              ></li>
              {% endfor %}
            </ol>
            <div class="carousel-inner" role="listbox">
              {% for pic in post.postimages_set.all %}
              {% ifequal forloop.counter 1 %}
              <div class="carousel-item active">
              {% else %}
              <div class="carousel-item">
              {% endifequal %}
                {% thumbnail pic.image 900x350 crop as thumb %}
                <img style="display: block; margin: 0 auto;" class="d-block img-fluid" src="{{ thumb.url }}" width="{{ thumb.width }}" height="{{ thumb.height }}" alt="" />
              </div>
              {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span><i class="fa fa-angle-left arrow" style="font-size:36px"></i></span>
              <span  class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span><i class="fa fa-angle-right" style="font-size:36px"></i></span>
              <span  class="sr-only">Next</span>
            </a>
          </div>

            <div class="card-body">
              <h2 class="card-title">{{ post.title }}</h2>
	      <a display: inline-block font size="3">
          {% if post.offering %}
            Offered
          {% else %}
            Wanted
          {% endif %}
          by:&nbsp</a><a float:right href="{% url 'account:profile' user_id=post.poster_id %}">{{ post.poster }}</a>&nbsp&nbsp<time>{{ post.time }}</time>&nbsp

          {% ifequal request.user.pk post.poster_id %}
		        <a class="w3-btn w3-black w3-disabled" href="{% url 'posts:delete_post' post_id=post.pk %}">Delete Post</a></br>


          <form method="POST" action="{% url 'posts:settings' post_id=post.pk %}">
            <h5>Open?</h5>
            {% csrf_token %}
	        <label class="switch">
  		    <input name="status" type="checkbox"
          {% if post.status %}
          checked
          {% endif %}>
          <span class="slider round"></span>
        </label>
        <button class="w3-btn w3-black" style="margin:auto; width:auto;" type="submit">Save Changes</button>
        </form>
            {% endifequal %}
              <h4>${{ post.price }}</h4> <hr>
              <p class="card-text">{{ post.description }}
            </div>
          </div>
          <!-- /.card -->

          <div class="card card-outline-secondary my-4">
            <div class="card-header">
              Comments
            </div>
            <div class="card-body">
              {% for comment in post.comments_set.all %}
              <p>{{ comment.text }}</p>
              <small class="text-muted">Posted by <a href="{% url 'account:profile' user_id=comment.user_id %}">{{ comment.user }}</a> on {{ comment.time }}</small>
              {% ifequal request.user.pk comment.user_id %}
              <br />
              <a class="w3-btn w3-black w3-disabled" href="{% url 'posts:delete_comment' comment_id=comment.pk %}">Delete Comment</a>
              {% endifequal %}
              <hr>
              {% endfor %}
              {% if request.user.is_authenticated %}
                <form method="POST" action="{% url 'posts:comment' post_id=post.pk %}">
                  {% csrf_token %}
                  <input type="text" name="comment" required /><br /><br />
                  <button type="submit" class="btn btn-success">Leave a Comment</button>
                </form>
              {% endif %}
            </div>
          </div>
          <!-- /.card -->

        </div>
        <!-- /.col-lg-9 -->

      </div>

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; UR-Sale 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>